// =====================================================================
// ملف بيانات المواقع والأقسام - دليل أرباحي المعتمد
// هذا الملف منفصل عن index.html لتسهيل إضافة/تعديل المواقع والأقسام
// بدون الحاجة لفتح أو لمس ملف index.html نهائياً.
//
// كل ما تحتاجه لإضافة موقع جديد أو قسم جديد موجود هنا فقط.
// شاهد ملف sites-data.sample.js كمرجع/قالب تجريبي لشرح طريقة الإضافة
// دون التأثير على هذا الملف الحقيقي.
// =====================================================================
    const dataset = [
      
        {categoryKey: "trending",
        categoryTitleAr: "🔥 المواقع الرائجة والجديدة (الأعلى تقييماً)",
        categoryTitleEn: "🔥 Trending & New Platforms",
        isTrending: true,
        sites: [ 
		 
{id: 1,  name: "luckywatch", 
      url: "https://luckywatch.pro/u/0zcas", 
      daily: 0.30, 
      currency: "USD", 
      category: "tasks", 
      startDate: "2025-05-14", 
      timeMinutes: 40,
      minWithdraw: "$0.1",
      description: "تطبيق تلقائي لمشاهدة الفيديو والربح مع منصة لسطح المكتب والافضل تطبيق الهاتف لامكانية التشغيل التلقائي.",
      paymentLinks: ["faucetpay", "binance", "bybit", "cwallet", "okx",], 
      proof: "https://telegram.me/MajdEarn" 
    },
			    {id: 01,  name: "jumptask", 
      url: "https://www.jumptask.io/r/cidypycysive", 
      daily: 0.50, 
      currency: "USD", 
      category: "tasks", 
      startDate: "2022-01-03", 
      timeMinutes: 40,
      minWithdraw: "$1.00",
      description: "تطبيق ومنصة للربح من الانترنت والمهام ومشاهدة الفيديوهات علي اليوتيوب ومنصات السوشيال ميديا وزيارة المواقع اونلاين والبحث علي المواقع ومحركات البحث  واذا سجلت من قبل اكتب هذا الكود للحصول علي نسبة ١٠٪ اكثر علي المهام cidypycysive لا تتردد في ترك استفسارك وتركت لك شروحاتي علي القناة عن المنصة" ,
      paymentLinks: ["amazon", "aliexpress", "temu", "ebay", "walmart", "target", "steam", "netflix", "shein", "apple", "doordash", "paypal", "visa", "mastercard", "wise", "revolut", "venmo", "skrill", "base", "bitcoin", "ethereum", "tron"],
 "proof": "https://telegram.me/MajdEarn"},
{"id": 2,"name": "fomoearn",
  "url": "https://fomoearn.com/r/NZvQDamq",
  "daily": 0.25,
  "currency": "USD",
  "category": "tasks",
  "startDate": "2026-08-09",
  "timeMinutes": 60,
  "minWithdraw": "$0.00",
  "description": "تطبيق تلقائي لمشاهدة الفيديو والربح مع منصة لسطح المكتب والافضل تطبيق الهاتف لامكانية التشغيل التلقائي اسرع من لاكي واتش ويفضل العمل علي الاثنان معا.",
  "paymentLinks": [
    "paypal",
    "faucetpay",
    "binance","bybit",
    "cwallet",
    "okx"],
  "proof": "https://t.me/your_channel/3"},

 {"id": 4,"name": "viefaucet",
  "url": "https://viefaucet.com?r=653cd638e76a41ee3e179b5f",
  "daily": 0.20,
  "currency": "USD",
  "category": "PTC",
  "startDate": "2020-02-02",
  "timeMinutes": 60,
  "minWithdraw": "$0.005",
  "description": "اعمل عليه منذ 2023 تربح من مشاهدة الاعلانات والصنبور كل 4 دقائق اضافة الي الهدايا اليومية من خلال اكواد التيليجرام والتحديات ولا تنسي البونص اليومي لرفع قيمة ارباحك اليوميه الموقع يحقق اعلي من 20 سنت بكثير ولكن ذلك الافضل والثابت",
  "paymentLinks": [
   "faucetpay",
    "cwallet",],
  "proof": "https://telegram.me/MajdEarn"
},
{id: 5,name: "SproutGigs", 
            url: "https://sproutgigs.com/?a=6d09da18", 
            daily: 1, 
            currency: "USD", 
            category: "tasks", 
            startDate: "2020-01-17", 
            timeMinutes: 60,
            minWithdraw: "$5.00",
            description: "منصة رائدة للعمل الحر المصغر وتنفيذ المهام السريعة مقابل أرباح مرتفعة.",
            paymentLinks: [
              "litecoin", "paypal","binance","faucetpay"], 
            proof: "https://telegram.me/MajdEarn"},
	
{"id": 6,name: "Food Fight", 
    url: "https://bln.gg/KQJ-PT9-BFK",
    daily: 0.15,
    currency: "USD",
    category: "games",
    startDate: "2021-03-15",
    timeMinutes: 20,
    minWithdraw: "$0.05",
    description: "لعبة تصويب السكاكين نحو الطعام الممتعة لجمع نقاط Bling وتحويلها مباشرة إلى بيتكوين أو إيثريوم.",
    paymentLinks: ["coinbase", "paypal"],
    proof: "https://telegram.me/MajdEarn"},
  		
	]},
        {categoryKey: "ptc",
        categoryTitleAr: "منصات الإعلانات والصنابير",
        categoryTitleEn: "PTC & Faucet Sites",
        sites: [
  {id: 100,name: "faucetpay", 
            url: "https://faucetpay.io/r/affiliatesignup", 
            daily: 0.15, 
            currency: "USD", 
            category: "ptc", 
            startDate: "2019-11-10", 
            timeMinutes: 15,
            minWithdraw: "$0.00",
            description: "موقع ومحفظة في نفس الوقت وضعت لك الافضل ربحا وثبات عليه وهي اعلانات PTC المضمونة وهناك طرق اخري للربح من عليه.",
            paymentLinks: ["faucetpay",
    "binance","bybit",
    "cwallet",
    "okx"], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 101,name: "bestchange", 
            url: "https://www.bestchange.com/?p=96287", 
            daily: 1.0, 
            currency: "USD", 
            category: "ptc", 
            startDate: "2007-01-01", 
            timeMinutes: 1,
            minWithdraw: "$1.00",
            description: "موقع ممتاز للربح من خلال الزيارات فقط كل زائر من 1 سنت لاعلي من 10 سنت وعند تكرار الزيارات تحسب عمولات + عمولات المعاملات علي الموقع.",
            paymentLinks: ["faucetpay",
    "binance","bybit",
    "cwallet",
    "okx"], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 102,name: "earn-trump", 
            url: "https://earn-trump.com/?r=04acb066b4aa", 
            daily: 0.30, 
            currency: "trump", 
            category: "faucet", 
            startDate: "2025-01-21", 
            timeMinutes: 0.3,
            minWithdraw: "$0.00",
            description: "صنبور تعدين عملة ترامب كل 3 ثواني ",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 103,name: "faucetpayz", 
            url: "https://faucetpayz.com/ref/MAJDFATIHY", 
            daily: 0.01, 
            currency: "USD", 
            category: "PTC", 
            startDate: "2023-05-14", 
            timeMinutes: 15.0,
            minWithdraw: "$0.00550",
            description: "صنبور ومشاهدة اعلانات جيد في السحب من اول يوم",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 104,name: "kiddyearner", 
            url: "https://kiddyearner.com/?r=6a9478ea0b2fa33d32218670", 
            daily: 0.24, 
            currency: "USD", 
            category: "PTC", 
            startDate: "2020-02-20", 
            timeMinutes: 15.0,
            minWithdraw: "$0.00",
            description: "صنبور ومشاهدة اعلانات جيد في السحب من اول يوم فوري للسحب",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 105,name: "limefaucet", 
            url: "https://limefaucet.com/ref/tvFBxk9c4n7Rpd6X", 
            daily: 0.015, 
            currency: "USD", 
            category: "PTC", 
            startDate: "2026-05-23", 
            timeMinutes: 6.0,
            minWithdraw: "$0.00",
            description: "صنبور ومشاهدة اعلانات جيد في السحب من اول يوم فوري للسحب",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 106,name: "btcadspace", 
            url: "https://btcadspace.com/ref/majdfatihy", 
            daily: 0.0048, 
            currency: "USD", 
            category: "PTC", 
            startDate: "2020-11-12", 
            timeMinutes: 6.0,
            minWithdraw: "$0.004",
            description: "صنبور ومشاهدة اعلانات جيد في السحب من اول يوم فوري للسحب",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  {id: 107,name: "coinli", 
            url: "https://coinli.net/i/16020", 
            daily: 0.03, 
            currency: "USD", 
            category: "PTC", 
            startDate: "2026-07-25", 
            timeMinutes: 5.0,
            minWithdraw: "$0.01",
            description: "صنبور ومشاهدة اعلانات جيد في السحب من اول يوم فوري للسحب",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          }, 
  { id: 108, name: "doge-faucet", 
            url: "https://beefaucet.org/doge-faucet/?r=fthymajd370@gmail.com", 
            daily: 0.015, 
            currency: "DOGE", 
            category: "faucet", 
            startDate: "2023-08-21", 
            timeMinutes: 1,
            minWithdraw: "$0.00",
            description: "صنبور كل دقيقة والربح المذكور كل 12 ساعه والسحب فوري بدون حد ادني.",
            paymentLinks: ["faucetpay",], 
            proof: "https://t.me/MajdEarn" 
          },
  { "id": 109, "name": "usdt-faucet",
    "url": "https://beefaucet.org/usdt-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.018,
    "currency": "USDT",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور USDT كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay",],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 110, "name": "trx-faucet",
    "url": "https://beefaucet.org/trx-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.017,
    "currency": "TRX",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور TRX كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 111, "name": "xrp-faucet",
    "url": "https://beefaucet.org/xrp-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.015,
    "currency": "XRP",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور XRP كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 112, "name": "btc-faucet",
    "url": "https://beefaucet.org/btc-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.000,
    "currency": "BTC",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور BTC كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 113, "name": "eth-faucet",
    "url": "https://beefaucet.org/eth-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.018,
    "currency": "ETH",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور ETH كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 114, "name": "bnb-faucet",
    "url": "https://beefaucet.org/bnb-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.021,
    "currency": "BNB",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور BNB كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 115, "name": "sol-faucet",
    "url": "https://beefaucet.org/sol-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.018,
    "currency": "SOL",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور SOL كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 116, "name": "usdc-faucet",
    "url": "https://beefaucet.org/usdc-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.018,
    "currency": "USDC",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور USDC كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 117, "name": "ton-faucet",
    "url": "https://beefaucet.org/ton-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.015,
    "currency": "TON",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور TON كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 118, "name": "bch-faucet",
    "url": "https://beefaucet.org/bch-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.016,
    "currency": "BCH",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور BCH كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 119, "name": "ada-faucet",
    "url": "https://beefaucet.org/ada-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.017,
    "currency": "ADA",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور ADA كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 120, "name": "ltc-faucet",
    "url": "https://beefaucet.org/ltc-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.018,
    "currency": "LTC",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور LTC كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 121, "name": "matic-faucet",
    "url": "https://beefaucet.org/matic-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.015,
    "currency": "MATIC",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور MATIC كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 122, "name": "xmr-faucet",
    "url": "https://beefaucet.org/xmr-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.015,
    "currency": "XMR",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور XMR كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 123, "name": "xlm-faucet",
    "url": "https://beefaucet.org/xlm-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.016,
    "currency": "XLM",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور XLM كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 124, "name": "zec-faucet",
    "url": "https://beefaucet.org/zec-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.022,
    "currency": "ZEC",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور ZEC كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 125, "name": "dash-faucet",
    "url": "https://beefaucet.org/dash-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.025,
    "currency": "DASH",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور DASH كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 126, "name": "dgb-faucet",
    "url": "https://beefaucet.org/dgb-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.017,
    "currency": "DGB",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور DGB كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  },
  { "id": 127, "name": "fey-faucet",
    "url": "https://beefaucet.org/fey-faucet/?r=fthymajd370@gmail.com",
    "daily": 0.010,
    "currency": "FEY",
    "category": "faucet",
    "startDate": "2023-08-21",
    "timeMinutes": 1,
    "minWithdraw": "$0.00",
    "description": "صنبور FEY كل دقيقة والسحب فوري على FaucetPay بدون حد ادني.",
    "paymentLinks": ["faucetpay"],
    "proof": "https://t.me/MajdEarn"
  }

]},
{categoryKey: "earn game",
        categoryTitleAr: "🤝 العاب الهاتف",
        categoryTitleEn: "🤝 game",
        sites: [
				{ "id": 600, "name": "Food Fight",
				url: "https://bln.gg/KQJ-PT9-BFK",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "برنامج أفيليت منصات التداول والخيارات لتسويق الخدمات وجذب العملاء.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 601, "name": "Ethereum Blast",
				url: "https://bln.gg/2QM-498-XSK",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Ethereum Blast للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 602, "name": "Dungeon Bitcoin Blast",
				url: "https://bln.gg/Y7F-W7W-MJQ",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Dungeon Bitcoin Blast للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 603, "name": "Sweet Bitcoin",
				url: "https://bln.gg/DRW-GG9-0BX",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Sweet Bitcoin للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 604, "name": "Bitcoin Pop",
				url: "https://bln.gg/3GM-29W-BK5",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Bitcoin Pop للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 605, "name": "Bitcoin Blocks",
				url: "https://bln.gg/SD9-5XZ-H2A",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Bitcoin Blocks للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 606, "name": "Bitcoin Blast",
				url: "https://bln.gg/TE9-E10-EV0",
				daily: 0.10,
				currency: "USD",
				category: "games",
				startDate: "2020-01-13",
				timeMinutes: 1,
				minWithdraw: "$00.03",
				description: "تطبيق Bitcoin Blast للربح اليومي مع سحب فوري.",
				paymentLinks: [
				"paypal",
				"coinbase",
				"walletofsatoshi"
				],
				proof: "https://t.me/your_channel/301"
			}
			]
		},
      {categoryKey: "affiliate-platforms",
        categoryTitleAr: "🤝 قسم الأفيليت والتسويق للمواقع والمنصات",
        categoryTitleEn: "🤝 Affiliate & Trading Platforms",
        sites: [
          {id: 200,name: "ExpertOption", 
            url: "https://expertoption-track.com/119223252", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "2014-01-01", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "برنامج أفيليت منصات التداول والخيارات لتسويق الخدمات وجذب العملاء.",
               paymentLinks: ["faucetpay", "binance", "bybit", "cwallet", "okx",], 
				proof: "https://telegram.me/MajdEarn" 
          },
		  {id: 205,name: "headway", 
            url: "https://headway.partners/promo/bonus-150/?hwp=b161ef", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "1994-12-28", 
            timeMinutes: 1,
            minWithdraw: "$1.00",
            description: "برنامج أفيليت منصات التداول والخيارات لتسويق الخدمات وجذب العملاء.",
               paymentLinks: ["faucetpay", "binance", "bybit", "cwallet", "okx",], 
				proof: "https://telegram.me/MajdEarn" 
          },
          {id: 201,name: "Pocket Option", 
            url: "https://u3.shortink.io/login?social=Google&utm_campaign=780866&utm_source=affiliate&utm_medium=sr&a=LRM5iO8kdh4nqY&al=1794573&ac=web-affilite&cid=978970&code=WELCOME50", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "2017-05-12", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "تسويق بالعمولة لمنصة تداول شهيرة مع نسب أرباح عالية.",
            paymentLinks: ["binance"], 
            proof: "https://t.me/your_channel/302" 
          },
          {id: 202,name: "Olymp Trade", 
            url: "https://olymptrade.com/pages/referral/?rf=72093157", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "2014-09-01", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "برنامج شركاء أوليمب تريد لتحقيق عمولات مستمرة من المتداولين.",
            paymentLinks: ["skrill", "visa"], 
            proof: "https://t.me/your_channel/303" 
          },
          {id: 203,name: "Amazon Associates", 
            url: "https://affiliate-program.amazon.com", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "1996-07-01", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "أكبر برنامج تسويق بالعمولة لبيع المنتجات والسلع عبر أمازون.",
            paymentLinks: ["amazon", "paypal"], 
            proof: "https://t.me/your_channel/304" 
          },
          {id: 204,name: "Noon Affiliate", 
            url: "https://noon.com", 
            daily: 0.00, 
            currency: "EGP", 
            category: "affiliate", 
            startDate: "2017-12-01", 
            timeMinutes: 1,
            minWithdraw: "$100.00",
            description: "برنامج نون للتسويق بالعمولة في المنطقة العربية ومنتجات المتجر.",
            paymentLinks: ["noon", "vodafone"], 
            proof: "https://t.me/your_channel/305" 
          },
		  { "id": 701, "name": "RedotPay",
				url: "https://url.hk/i/ar/rs8k8",
				customIcon: "",
				daily: 0.00,
				currency: "USD",
				category: "finance",
				startDate: "2023-04-01",
				timeMinutes: 1,
				minWithdraw: "$00.00",
				description: "بطاقة فيزا وافتراضية للتدفقات المالية والعملات الرقمية.",
				paymentLinks: [
				"redotpay"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 702, "name": "Rizon",
				url: "https://getrizon.sng.link/Eshdf/1cro/dfwn?ref=XAAUEUQ&_forward_params=2",
				customIcon: "",
				daily: 0.00,
				currency: "USD",
				category: "finance",
				startDate: "2025-02-14",
				timeMinutes: 1,
				minWithdraw: "$00.00",
				description: "تطبيق للحصول على فيزا افتراضية للشراء والتسوق عبر الإنترنت.",
				paymentLinks: [
				"rizon"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 703, "name": "Thndr",
				url: "https://thndr.app.link/majdfatihy",
				customIcon: "",
				daily: 0.20,
				currency: "EGP",
				category: "investing",
				startDate: "2026-01-01",
				timeMinutes: 1,
				minWithdraw: "$00.00",
				description: "منصة للاستثمار والتداول في البورصة وصناديق الاستثمار.",
				paymentLinks: [
				"thndr"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 704, "name": "TeraBox",
				url: "https://www.terabox.com/referral/4400541698368",
				customIcon: "",
				daily: 0.13,
				currency: "USD",
				category: "storage",
				startDate: "2026-01-01",
				timeMinutes: 1,
				minWithdraw: "$10.00",
				description: "منصة تخزين سحابي توفر مساحات مجانية وبرامج إحالة للربح كل مستخدم رينج 12 الي 25 سنت علي حسب الدولة.",
				paymentLinks: [
				"terabox"
				],
				proof: "https://t.me/your_channel/301"
			},
				{ "id": 705, "name": "Grey",
				url: "https://greyapp.page.link/jixhVD5wH6mdykEY7",
				customIcon: "",
				daily: 0.00,
				currency: "USD",
				category: "banking",
				startDate: "2026-01-01",
				timeMinutes: 1,
				minWithdraw: "$00.00",
				description: "حساب بنكي أمريكي وبطاقة فيزا لاستلام الأموال وتحويلها دولياً.",
				paymentLinks: [
				"grey"
				],
				proof: "https://t.me/your_channel/301"
			}
        ]},
      
      {categoryKey: "coupons-section",
        categoryTitleAr: "🎟️ قسم الربح والتوفير من الكوبونات والخصومات",
        categoryTitleEn: "🎟️ Coupons & Cashback Earning",
        sites: [
          {id: 300,name: "Letyshops", 
            url: "https://letyshops.com/winwin?ww=46763893", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "2014-06-12", 
            timeMinutes: 1,
            minWithdraw: "$5.00",
            description: "موقع كاش باك وتوفير واسترداد أموال عند التسوق من المتاجر الكبرى.",
            paymentLinks: ["paypal", "visa"], 
            proof: "https://t.me/your_channel/401" 
          },
          {id: 301,name: "Aliexpress Deals", 
            url: "https://aliexpress.com", 
            daily: 0.00, 
            currency: "USD", 
            category: "affiliate", 
            startDate: "2010-04-01", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "برنامج الكوبونات والعروض الترويجية لمنتجات علي إكسبريس.",
            paymentLinks: ["visa"], 
            proof: "https://t.me/your_channel/402" 
          }
        ]
      },
      {categoryKey: "services-courses",
        categoryTitleAr: "📚 قسم شراء الخدمات والكورسات وتطوير المهارات",
        categoryTitleEn: "📚 Services & Courses Marketplace",
        sites: [
          {id: 501,name: "Udemy Courses", 
            url: "https://udemy.com", 
            daily: 0, 
            currency: "USD", 
            category: "tasks", 
            startDate: "2010-05-01", 
            timeMinutes: 1,
            minWithdraw: "$0.00",
            description: "منصة تعليمية ضخمة لشراء كورسات وتطوير مهارات البرمجة والتسويق.",
            paymentLinks: ["paypal", "visa"]
          },
		  {id: 503,name: "nzmly Courses", 
            url: "https://nzmly.to/BFsJhgjs", 
            daily: 0, 
            currency: "EGP", 
            category: "tasks", 
            startDate: "2025-07-18", 
            timeMinutes: 1,
            minWithdraw: "$2.00",
            description: "منصة تعليمية ضخمة لشراء كورسات وتطوير مهارات البرمجة والتسويق.",
           paymentLinks: [
  "instapay",
  "visa",
  "mastercard",
  "stripe",
  "vodafone_eg",
  "orange_eg",
  "etisalat_eg",
  "we_eg",
  "fawry",
  "paypal",]
          },
          {id: 502,name: "Fiverr Services", 
            url: "https://fiverr.com", 
            daily: 0, 
            currency: "USD", 
            category: "tasks", 
            startDate: "2010-02-01", 
            timeMinutes: 1,
            minWithdraw: "$10.00",
            description: "شراء وبيع الخدمات المصغرة الاحترافية لدعم وتطوير مشاريعك.",
            paymentLinks: ["paypal", "payoneer"]
          }
        ]
      },
      {categoryKey: "wallets",
        categoryTitleAr: "👛 قسم المحافظ الرقمية المعتمدة للسحب عليها",
        categoryTitleEn: "👛 Recommended Crypto Wallets",
        isWalletSection: true,
        sites: [
          {id: 400,name: "FaucetPay Wallet", 
            url: "https://faucetpay.io/r/affiliatesignup", 
            daily: 0, 
            currency: "BTC", 
            category: "faucet", 
            startDate: "2019-11-20", 
            timeMinutes: 1,
            description: "محفظة وسيطة وتجميعية مصغرة لاستقبال العملات الرقمية من الصنابير مجاناً."
          },
		  
  {id: 404, name: "Binance", url:
  "https://www.binance.com/register?ref=AFFILIATE1&utm_medium=app_share_link", daily: 0, currency: "USDT", category: "exchange", startDate: "2017-07-14", timeMinutes: 0, description: "منصة عالمية لتداول العملات الرقمية والعقود الآجلة وشراء الكريبتو."},
  {id: 401, name: "Bybit", url: 
"https://www.bybitglobal.com/ar-SA/sign-up?affiliate_id=118303&group_id=0&group_type=1", daily: 0, currency: "USDT", category: "exchange", startDate: "2018-03-01", timeMinutes: 0, description: "منصة تداول وتخزين العملات الرقمية وتوفر أدوات متقدمة لتداول المشتقات."},
  {id: 402, name: "Cwallet", url:
  "https://cwallet.com/referralweb/CAzXK2qr", daily: 0, currency: "USDT", category: "wallet", startDate: "2021-01-01", timeMinutes: 1, description: "محفظة رقمية متعددة الشبكات تدعم أدوات التوزيع المجاني والبونص."},
  {id: 403, name: "OKX", url:
  "https://www.okx.com/join/MAJDWEB", daily: 0, currency: "USDT", category: "exchange", startDate: "2017-05-01", timeMinutes: 0, description: "منصة عالمية رائدة لتداول العملات الرقمية وخدمات الـ Web3."},
{id: 405, name: "btse", url:
  "https://www.btse.com/referral/ijSyv37p", daily: 0, currency: "USDT", category: "wallet", startDate: "2002-03-29", timeMinutes: 1, description: "منصة لتداول وتخزين العملات الرقمية توفر أيضاً مكافآت ترحيبية وبرنامج إحالة."},
   {id: 406, name: "Sweat", url:
  "https://swe.at/c/BEgvxVbpo3", daily: 0, currency: "USDT", category: "wallet", startDate: "2022-01-01", timeMinutes: 0, description: "تطبيق يحوّل خطواتك اليومية إلى عملة SWEAT الرقمية القابلة للتحويل والسحب."}
        ]
      }
    ];
