const WITHDRAWAL_METHODS = {
  "faucetpay": { url: "https://faucetpay.io/r/affiliatesignup", icon: "" },
  "binance": { url: "https://www.binance.com/register?ref=AFFILIATE1&utm_medium=app_share_link", icon: "" },
  "bybit": { url: "https://www.bybitglobal.com/ar-SA/sign-up?affiliate_id=118303&group_id=0&group_type=1", icon: "" },
  "cwallet": { url: "https://cwallet.com/referralweb/CAzXK2qr", icon: "" },
  "okx": { url: "https://www.okx.com/join/MAJDWEB", icon: "" },
  "btse": { url: "https://www.btse.com/referral/ijSyv37p", icon: "" },
  "sweat": { url: "https://swe.at/c/BEgvxVbpo3", icon: "" },
  "paypal": { url: "https://paypal.com", icon: "" },
  "coinbase": { url: "https://coinbase.com", icon: "" },
  "litecoin": { url: "https://litecoin.org", icon: "" },
  "walletofsatoshi": { url: "https://www.walletofsatoshi.com", icon: "" },
  "skrill": { url: "https://skrill.com", icon: "" },
  "visa": { url: "https://visa.com", icon: "" },
  "mastercard": { url: "https://mastercard.com", icon: "" },
  "amazon": { url: "https://amazon.com", icon: "" },
  "noon": { url: "https://noon.com", icon: "" },
  "vodafone": { url: "https://vodafone.com", icon: "" },
  "vodafone_eg": { url: "https://vodafone.com.eg", icon: "" },
  "orange_eg": { url: "https://orange.eg", icon: "" },
  "etisalat_eg": { url: "https://etisalat.eg", icon: "" },
  "we_eg": { url: "https://we.eg", icon: "" },
  "fawry": { url: "https://fawry.com", icon: "" },
  "instapay": { url: "https://www.instapay.eg", icon: "" },
  "stripe": { url: "https://stripe.com", icon: "" },
  "payoneer": { url: "https://payoneer.com", icon: "" },
  "terabox": { url: "https://www.terabox.com", icon: "" },
  "thndr": { url: "https://thndr.app", icon: "" },
  "grey": { url: "https://grey.co", icon: "" },
  "redotpay": { url: "https://url.hk/i/ar/rs8k8", icon: "" },
  "rizon": { url: "https://getrizon.sng.link/Eshdf/1cro/dfwn?ref=XAAUEUQ&_forward_params=2", icon: "" },
  "aliexpress": { url: "", icon: "" },
  "temu": { url: "", icon: "" },
  "ebay": { url: "", icon: "" },
  "walmart": { url: "", icon: "" },
  "target": { url: "", icon: "" },
  "steam": { url: "", icon: "" },
  "netflix": { url: "", icon: "" },
  "shein": { url: "", icon: "" },
  "apple": { url: "", icon: "" },
  "doordash": { url: "", icon: "" },
  "wise": { url: "", icon: "" },
  "revolut": { url: "", icon: "" },
  "venmo": { url: "", icon: "" },
  "base": { url: "", icon: "" },
  "bitcoin": { url: "", icon: "" },
  "ethereum": { url: "", icon: "" },
  "tron": { url: "", icon: "" },
  "webmoney": { url: "", icon: "" },
  "volet": { url: "", icon: "" },
  "bank card (ru)": { url: "", icon: "" },
  "bank card (uz)": { url: "", icon: "" },
  "tether (bep20)": { url: "", icon: "" },
  "tether (ton)": { url: "", icon: "" },
  "gram (formerly toncoin)": { url: "", icon: "" },
  "dogecoin": { url: "", icon: "" },
  "fkwallet": { url: "", icon: "" }
};
